### ISSUE TITLE
List of exploration activities

### ISSUE THREAD

**Issue by jasonckramer** [IcyLemonZ/pf2e-exploration-activities#1]
Is it possible to see what is being offered to players as exploration activities? Can the list of options be added to/subtracted? Thanks!

**Comment by IcyLemonZ** [comment]
The list is currently hardcoded in the explorationActivity(actor) method [here](https://github.com/IcyLemonZ/pf2e-exploration-activities/blob/4cda51e21637b0c98c73c4156d028bfe3b13bcac/scripts/scripts.js#L8). To the players, it looks like this.

![image](https://user-images.githubusercontent.com/73080231/143683578-1b0d1399-c42e-4db4-81a5-513a3ab23872.png)

There's no simple way of adding to, or removing, from that list at the moment short of editing the file locally.

**Comment by jasonckramer** [comment]
Thank you for the response!
