### ISSUE TITLE
Any chance of merging with PF2E Exploration Effects?

### ISSUE THREAD

**Issue by Unikatze** [IcyLemonZ/pf2e-exploration-activities#4]
Cora's Module doesn't have a way to ask player what they're doing. But it does have macros to add an effect on which Exploration activity the player is currently doing. 

Would it be possible to enable it in your mod so that when my player selects "Avoid Notice" they get the Avoid Notice effect from Cora's Module?

**Comment by Ironxxx** [comment]
I second this, that would be great

**Comment by MarkPearce** [comment]
updated (and released) the fork for V10, merging with main and submitted a PR
https://github.com/MarkPearce/pf2e-exploration-activities/releases/latest/download/module.json

**Comment by ThunderousLeft** [comment]
I hope to see this PR merged soon! This would be great.

**Comment by MarkPearce** [comment]
In the mean time you could link foundry to my repo with this manifest 

https://github.com/MarkPearce/pf2e-exploration-activities/releases/latest/download/module.json

**Comment by IcyLemonZ** [comment]
Sorry for the silence, had a few irl priorities. I'll try and take a look at the PR this week.

**Comment by IcyLemonZ** [comment]
@MarkPearce PR has been merged into main. The feature is now present as of v1.2.1. Apologies for the delay.

**Comment by ThunderousLeft** [comment]
Thanks!!
